<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipeline/blob/main/notebook_tipos_seguro/ETL_Tipos_Seguro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipeline/refs/heads/main/datos/raw/tipos_seguro.csv"

df = pd.read_csv(url)
df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [2]:
#EXPLORACION DE DATOS
print(f"Forma del dataset: {df.shape}")
print(f"Columnas detectadas: {df.columns}")
print("\nInformación general:")
df.info()
print("\nConteo de nulos:")
print(df.isnull().sum())

Forma del dataset: (12, 4)
Columnas detectadas: Index(['id_tipo_seguro', 'tipo', 'categoria', 'riesgo_base'], dtype='object')

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

Conteo de nulos:
id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [3]:
#LIMPIEZA DATOS
tipos_seguro = df.copy()

# 1. Estandarizar nombres de columnas
tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

# 2. Limpiar espacios en blanco en textos
for col in tipos_seguro.select_dtypes(include='object').columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

# 3. Convertir vacíos en Nulos reales (<NA>)
tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)
tipos_seguro = tipos_seguro.replace('nan', pd.NA)

# 4. Estandarizar (Ej: 'VIDA' -> 'Vida')
tipos_seguro['tipo'] = tipos_seguro['tipo'].str.capitalize()
tipos_seguro['categoria'] = tipos_seguro['categoria'].str.capitalize()

# 5. Eliminar duplicados
tipos_seguro = tipos_seguro.drop_duplicates()

In [4]:
#SEPARADOR DATOS VALIDOS Y RECHAZADOS
# Definimos que para que un tipo de seguro sea válido, debe tener categoría y riesgo
validos = tipos_seguro[
    tipos_seguro['categoria'].notna() &
    tipos_seguro['riesgo_base'].notna()
].copy()

In [5]:
#Los que tienen nulos en categoría o riesgo se van a rechazados
rechazados = tipos_seguro[
    tipos_seguro['categoria'].isna() |
    tipos_seguro['riesgo_base'].isna()
].copy()

print(f"Válidos: {len(validos)} | Rechazados: {len(rechazados)}")

Válidos: 9 | Rechazados: 3

In [6]:
#MOTIVO RECHAZO
def motivo(row):
    motivos = []
    if pd.isna(row['categoria']):
        motivos.append("categoria_vacia")
    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_base_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

# Verificamos los rechazados
display(rechazados.head())

,id_tipo_seguro,tipo,categoria,riesgo_base,motivo_rechazo
3,4,Industrial,Personal,<NA>,riesgo_base_vacio
8,9,Accidentes,<NA>,5.68,categoria_vacia
11,12,Agrícola,<NA>,<NA>,"categoria_vacia,riesgo_base_vacio"

In [7]:
#EXPORTACION
validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

In [8]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 61.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [9]:
##CARGAR EN POSTGRE
validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

9

In [10]:
rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

3

In [11]:
df_validado = pd.read_sql("SELECT * FROM tipos_seguro_curated LIMIT 10", engine)
display(df_validado)
print("\nRegistros en la tabla de Rechazados (Auditoría):")
df_rechazados_db = pd.read_sql("SELECT * FROM tipos_seguro_rejects", engine)
display(df_rechazados_db)

   id_tipo_seguro        tipo    categoria riesgo_base
0               1        Pyme     Familiar           -
1               2  Industrial  Empresarial        4.68
2               3  Industrial     Familiar        5.10
3               5        Auto  Empresarial        9.07
4               6  Industrial  Empresarial        2.52
5               7       Salud     Personal        0.92
6               8   Educación  Empresarial        7.42
7              10      Dental     Especial        2.70
8              11        Auto  Empresarial        4.33

Registros en la tabla de Rechazados (Auditoría):

,id_tipo_seguro,tipo,categoria,riesgo_base,motivo_rechazo
0,4,Industrial,Personal,None,riesgo_base_vacio
1,9,Accidentes,None,5.68,categoria_vacia
2,12,Agrícola,None,None,"categoria_vacia,riesgo_base_vacio"