<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipeline/blob/main/notebook_siniestros/ETL_Siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
url="https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipeline/refs/heads/main/datos/raw/siniestros.csv"
df = pd.read_csv(url)
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [4]:
#EXPLORACION DE DATOS
print(f"Forma del dataset: {df.shape}")
print(f"Columnas detectadas: {df.columns}")
print("\nInformación general:")
df.info()
print("\nConteo de nulos:")
print(df.isnull().sum())

Forma del dataset: (4620, 5)
Columnas detectadas: Index(['id_siniestro', 'id_poliza', 'fecha_siniestro', 'monto_siniestro',
       'estado'],
      dtype='object')

Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

Conteo de nulos:
id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [5]:
#LIMPIEZA DE DATOS
siniestros_limpio = df.copy()

# 1. Normalizar nombres de columnas
siniestros_limpio.columns = siniestros_limpio.columns.str.strip().str.lower()

# 2. Limpieza de strings en columnaS
for col in siniestros_limpio.select_dtypes(include='object').columns:
    siniestros_limpio[col] = siniestros_limpio[col].astype(str).str.strip()

# 3. Transformación de tipos de datos
siniestros_limpio['fecha_siniestro'] = pd.to_datetime(siniestros_limpio['fecha_siniestro'], errors='coerce')

# Convertimos monto_siniestro a número
siniestros_limpio['monto_siniestro'] = pd.to_numeric(siniestros_limpio['monto_siniestro'], errors='coerce')

if 'estado' in siniestros_limpio.columns:
    siniestros_limpio['estado'] = siniestros_limpio['estado'].str.upper()

# 5. Reemplazar valores basura por Nulos oficiales
siniestros_limpio = siniestros_limpio.replace(['nan', 'None', '', 'N/A'], pd.NA)
siniestros_limpio = siniestros_limpio.replace(r'^\s*$', pd.NA, regex=True)

# 6. Eliminar duplicados
siniestros_limpio = siniestros_limpio.drop_duplicates()
print(" Limpieza de Siniestros completada.")
print(f"Nuevos nulos detectados en Monto: {siniestros_limpio['monto_siniestro'].isna().sum()}")

 Limpieza de Siniestros completada.
Nuevos nulos detectados en Monto: 2699

/tmp/ipykernel_663/1129755608.py:12: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros_limpio['fecha_siniestro'] = pd.to_datetime(siniestros_limpio['fecha_siniestro'], errors='coerce')

In [6]:
#SEPARADOR DATOS VALIDOS Y RECHAZADOS
columnas_clave = ['id_poliza', 'fecha_siniestro', 'monto_siniestro', 'estado']

validos = siniestros_limpio[
    siniestros_limpio[columnas_clave].notna().all(axis=1)
].copy()

rechazados = siniestros_limpio[
    siniestros_limpio[columnas_clave].isna().any(axis=1)
].copy()

print(f"Total: {len(siniestros_limpio)}")
print(f"Válidos: {len(validos)}")
print(f"Rechazados: {len(rechazados)}")

Total: 4620
Válidos: 387
Rechazados: 4233

In [7]:
#MOTIVO RECHAZO
def motivo(row):
    motivos = []
    if pd.isna(row['id_poliza']):
        motivos.append("id_poliza_vacio")
    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_invalida")
    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_invalido_o_vacio")
    if pd.isna(row['estado']):
        motivos.append("estado_vacio")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

display(rechazados.head())

,id_siniestro,id_poliza,fecha_siniestro,monto_siniestro,estado,motivo_rechazo
1,2,2465,NaT,NaN,ABIERTO,"fecha_invalida,monto_invalido_o_vacio"
3,4,14299,NaT,274.63,ABIERTO,fecha_invalida
4,5,12908,NaT,NaN,RECHAZADO,"fecha_invalida,monto_invalido_o_vacio"
5,6,5107,NaT,NaN,NAN,"fecha_invalida,monto_invalido_o_vacio"
6,7,3379,NaT,NaN,ABIERTO,"fecha_invalida,monto_invalido_o_vacio"

In [8]:
#EXPORTACION
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

In [9]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 45.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [10]:
#CARGAR EN POSTGRE
validos.to_sql('siniestros_curated', engine,
  if_exists='append',
   index=False)

387

In [11]:
rechazados.to_sql('siniestros_rejects', engine,
 if_exists='append',
  index=False)

233

In [12]:
pd.read_sql(
    "SELECT * FROM siniestros_curated LIMIT 10",
    engine)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    ABIERTO
1             3      15785      2025-09-19           702.27    CERRADO
2             8      23824      2025-01-17          2736.20    ABIERTO
3            13       3716      2025-07-13         -4274.39  RECHAZADO
4            24      17180      2025-06-13          6183.83    CERRADO
5            27      22625      2025-03-07           141.77        NAN
6            33       2231      2025-09-21          2443.90  RECHAZADO
7            36      16929      2025-01-06          3649.94    CERRADO
8            45      15100      2025-01-27          8761.24    ABIERTO
9            66      14064      2025-03-25          9842.05    ABIERTO