<a href="https://colab.research.google.com/github/axelmartinezportillo/elt-data-pipeline/blob/main/notebook_polizas/ETL_Polizas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/axelmartinezportillo/elt-data-pipeline/refs/heads/main/datos/raw/polizas.csv"
df = pd.read_csv(url)
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [3]:
print(f"Forma del dataset: {df.shape}")
print(f"Columnas detectadas: {df.columns}")
print("\nInformación general :")
df.info()
print(df.isnull().sum())

Forma del dataset: (25150, 9)
Columnas detectadas: Index(['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor',
       'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision',
       'monto_asegurado'],
      dtype='object')

Información general :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB
id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [4]:
#LIMPIEZA DATOS
polizas_limpio = df.copy()

# 1. Normalizar encabezados
polizas_limpio.columns = polizas_limpio.columns.str.strip().str.lower()

# 2. Limpieza de strings en columnas de texto
for col in polizas_limpio.select_dtypes(include='object').columns:
    polizas_limpio[col] = polizas_limpio[col].astype(str).str.strip()

# 3. Transformación de tipos de datos
polizas_limpio['fecha_emision'] = pd.to_datetime(polizas_limpio['fecha_emision'], errors='coerce')

cols_financieras = ['prima', 'comision', 'monto_asegurado']
for col in cols_financieras:
    polizas_limpio[col] = pd.to_numeric(polizas_limpio[col], errors='coerce')

# 4. Reemplazo de vacíos por Nulos
polizas_limpio = polizas_limpio.replace(['nan', 'None', '', 'N/A'], pd.NA)
polizas_limpio = polizas_limpio.replace(r'^\s*$', pd.NA, regex=True)

# 5. Eliminar duplicados
polizas_limpio = polizas_limpio.drop_duplicates()

print("Limpieza de Pólizas finalizada.")
print(f"Registros después de duplicados: {len(polizas_limpio)}")

Limpieza de Pólizas finalizada.
Registros después de duplicados: 25150

In [5]:
#SEPARADOR DATOS VALIDOS Y RECHAZADOS
columnas_clave = ['fecha_emision', 'id_cliente', 'id_tipo_seguro', 'prima']

validos = polizas_limpio[
    polizas_limpio[columnas_clave].notna().all(axis=1)
].copy()

rechazados = polizas_limpio[
    polizas_limpio[columnas_clave].isna().any(axis=1)
].copy()

print(f"Válidos: {len(validos)}")
print(f"Rechazados: {len(rechazados)}")

Válidos: 2302
Rechazados: 22848

In [6]:
#MOTIVO RECHAZO
def motivo(row):
    motivos = []
    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_emision_invalida_o_vacia")
    if pd.isna(row['id_cliente']):
        motivos.append("id_cliente_nulo")
    if pd.isna(row['id_tipo_seguro']):
        motivos.append("tipo_seguro_desconocido")
    if pd.isna(row['prima']):
        motivos.append("prima_no_numerica_o_vacia")
    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)
display(rechazados[['id_poliza', 'motivo_rechazo']].head(10))

    id_poliza                                     motivo_rechazo
0           1  fecha_emision_invalida_o_vacia,prima_no_numeri...
1           2                          prima_no_numerica_o_vacia
2           3                     fecha_emision_invalida_o_vacia
3           4                     fecha_emision_invalida_o_vacia
4           5  fecha_emision_invalida_o_vacia,prima_no_numeri...
5           6                     fecha_emision_invalida_o_vacia
6           7                     fecha_emision_invalida_o_vacia
7           8                     fecha_emision_invalida_o_vacia
8           9  fecha_emision_invalida_o_vacia,prima_no_numeri...
10         11  fecha_emision_invalida_o_vacia,prima_no_numeri...

In [7]:
#EXPORTACION
validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

In [8]:
#CONECTAR RENDER
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:6r5AQWoE44HrllVAUznGZiLVeK6jjHfX@dpg-d6qu5ochg0os73b4g0v0-a.oregon-postgres.render.com/etl_seguros_fv1v"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [11]:
#CARGAR EN POSTGRE
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False,
    chunksize=500
)

2302

In [12]:
rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

848

In [13]:

df_db = pd.read_sql("SELECT COUNT(*) as total_registros FROM polizas_curated",
    engine)
print(f"Total de registros cargados: {df_db['total_registros'][0]}")

pd.read_sql("SELECT id_poliza, id_cliente, prima, fecha_emision FROM polizas_curated LIMIT 10",
            engine)

Total de registros cargados: 4604

   id_poliza  id_cliente    prima fecha_emision
0         10        2281   791.38    2026-01-24
1         26        2295   614.46    2025-07-29
2         32         388   822.52    2025-07-28
3         45        2278  1539.37    2025-12-11
4         49        1122   337.32    2025-08-11
5         50         717   518.78    2025-02-22
6         66        1352   776.33    2025-03-04
7         99         490   716.12    2025-05-12
8        104        3524   149.44    2025-10-20
9        122         318   726.10    2025-08-02